version: '3.9'
services:
  mariadb:
    build: requirements/mariadb
    env_file: .env
    container_name: mariadb
    restart: always
    volumes:
      - 'db:/var/lib/mysql'
    networks:
      - docker-network

networks:
  docker-network:
    name: inception_net
    driver: bridge

volumes:
  db:
    external: false
  wordpress:
    external: false
