version: '3.9'
services:
  nginx:
    build: requirements/nginx
    container_name: nginx
    ports: 
      - 443:443
    volumes:
      - /home/yihssan/data/html:/var/www/html/
    networks:
      - wordpress


  wordpress:
    build: requirements/wordpress
    container_name: wordpress
    volumes:
      - /home/yihssan/data/html:/var/www/html/
    restart: always
    networks:
      - wordpress
    env_file:
      - .env
    # depends_on:
    #   - mariadb


  # mariadb:
  #   build: requirements/mariadb
  #   container_name: mariadb
  #   volumes:
  #     - /home/yihssan/data/mysql:/var/lib/mysql
  #   restart: always
  #   ports:
  #     - 3306:3306
  #   env_file:
  #     - .env
  #   networks:
  #     - wordpress
    
networks:
  wordpress:
    driver: bridge
volumes:
  wordpress:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '/home/yihssan/data/html'
  nginx:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '/home/yihssan/data/html'
  # mariadb:
  #   driver: local
  #   driver_opts:
  #     type: 'none'
  #     o: 'bind'
  #     device: '/home/yihssan/data/mysql'