version: '3.9'
services:
  nginx:
    build: requirements/nginx
    container_name: nginx
    ports: 
      - 443:443
    volumes:
      - /home/yihssan/data/html:/var/www/html/
    networks:
      - wordpress


  wordpress:
    build: requirements/wordpress
    container_name: wordpress
    volumes:
      - /home/yihssan/data/html:/var/www/html/
    restart: always
    networks:
      - wordpress
    env_file:
      - .env

networks:
  wordpress:
    driver: bridge
volumes:
  wordpress:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '/home/yihssan/data/html'
  nginx:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '/home/yihssan/data/html'