FROM debian:buster

RUN apt update -y
RUN apt upgrade -y
RUN apt install mariadb-server -y
RUN apt install -y ufw iptables

RUN apt install -y ufw iptables

RUN ufw allow 3306

COPY tools/config.sh config.sh
RUN chmod +x config.sh
CMD ["sh", "config.sh"]